#title: AVERtek # your name photo (or website title) here
logo1: "images/BAHAY-LOGO-leaf-green-gold.png? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h1 style="color:#215732;"><p style="text-align:center;"><b>MEANS HOME</h1></b></p>
  <br><br>
  <h2 style="color:#A28D5B;"><em><p style="text-align:center;"><b>ENGAGE ALL 4 EXPERIENCES BELOW</h2></em></b></p>
  <br>
  <h3><p style="text-align:center;"<b>ENVISION: 3D APARTMENT</h3></b></p>
  <br><br> 
  <h3><p style="text-align:center;"<b>EXPLORE: MOBILE 4D AR TOUR</h3></b></p>
  <br><br>
  <h3><a href="https://alexanbahay.com/gallery/video/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/gallery/video/?utm_source=AVERtek&utm_medium=AR'); return false;"<b><p style="text-align:center;"> VIEW: LUXURY LIVING</h3></b></p></a> 
  <br><br>
  <h3><a href="https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR'); return false;"<b><p style="text-align:center;"> DISCOVER: VIP TOUR & FREE GIFT</h3></b></p></a>
  <h3 style="color:#A28D5B;"><em><p style="text-align:center;"><b>50% Off All Summer Long</h2></em></b></p>
  <br><br>
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-188164724-2 
